### ISSUE TITLE
Move parsing of fragments out of the query building

### ISSUE THREAD

**Issue by dieterve** [madewithlove/elasticsearcher#15]
We should able to use fragments in different contexts (like #3), at the moment it is restricted to Queries. This should also allow for doing more complex parsing (like #13). 

I would move to a `FragmentParser` that accepts an array and turns it into a "parsed" array. This way it can easily be re-used in other contexts.

I do see other parsers in the future (like ExceptionParser for extracting error info, or AggregationParser for simplifying aggregation results, ...). So adding a namespace `Parsers` sounds logical. We can move the ResultParsers under this.

**Comment by Anahkiasen** [comment]
> like ExceptionParser for extracting error info

Oh yes please, current errors spewed out by the SDKs are an horror, goddamn masive string mix of arrays and JSON
