### ISSUE TITLE
Error with indices manager

### ISSUE THREAD

**Issue by nWidart** [madewithlove/elasticsearcher#24]
Hello,

I'm getting the following error with executing a search:

```
Index [twitter] could not be found in the register of the indices manager.' in /home/vagrant/liftmetrixapp/vendor/madewithlove/elasticsearcher/src/Managers/IndicesManager.php:87
```

This index does exist in Elasticsearch though.

My search class is following the docs:

``` php
protected function setup()
{
    $this->searchIn('twitter');

    $body = [
        'query' => [
            'filtered' => [
                'filter' => [
                    'term' => ['user.screen_name' => 'NicolasWidart']
                ]
            ]
        ]
    ];
    $this->setBody($body);
}
```

And usage:

``` php
$query = new TotalNumberOfTweets($this->elasticSearcher);
$result = $query->run();
dd($result->getResults());
```

Did I miss something? 

Thanks

**Comment by bramdevries** [comment]
You need to also register the `Twitter` index class in the `indicesManager` like this:

https://github.com/madewithlove/elasticsearcher/blob/master/examples/bootstrap.php#L13-L15

**Comment by nWidart** [comment]
Yup done that, same thing.

```
$twitterIndex = new TwitterIndex();
app(ElasticSearcher::class)->indicesManager()->register($twitterIndex);
```

**Comment by bramdevries** [comment]
Are you doing this registration in a service provider and binding the `ElasticSearcher` instance to the IoC container as a singleton? If you don't, whenever you you inject an instance of `ElasticSearcher` it will be a new instance which doesn't contain the indices yet

**Comment by nWidart** [comment]
Indeed I am. Ah thanks, that makes sense, and works.

Thanks for your quick reply! :smile:
