### ISSUE TITLE
Improve bulk operation

### ISSUE THREAD

**Issue by tonysm** [madewithlove/elasticsearcher#37]
Right now the package loops over the data array and calls the index method on the [DocumentsManager](https://github.com/madewithlove/elasticsearcher/blob/master/src/Managers/DocumentsManager.php#L47-L52).

We could simply map the the dataset to so use a single HTTP call to ES by using the bulk operation describred here: https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_indexing_documents.html#_bulk_indexing

**Comment by hannesvdvreken** [comment]
@tonysm take into account this request could get very big. Better to loop a Traversable and when array exceeds a certain size, do a bulk index. 

What do you think?

**Comment by tonysm** [comment]
@hannesvdvreken I think that should be handled by the client using the library, no?

**Comment by hannesvdvreken** [comment]
You're right!
