### ISSUE TITLE
Tag the bugfix

### ISSUE THREAD

**Issue by JamesB797** [madewithlove/elasticsearcher#44]
Assuming I'm not missing something, even if I specify I want ^0.5 that won't give me the bugfix that's now in master, so I would need to require dev-master if I want to use it. That being the case, I'd like a new tag for the current commit (unless there's a valid reason to not make one).

**Comment by dieterve** [comment]
@JamesB797: I am planning a release tomorrow. Before I do that I need to fix the build, seems to be some version issues with phpunit on circleci.

**Comment by JamesB797** [comment]
Ok, thanks for the update!

**Comment by dieterve** [comment]
@JamesB797: I released `0.5.1` which includes your fix. Thanks again.
