### ISSUE TITLE
Intermediate support for deprecation of types in ES 6+

### ISSUE THREAD

**Issue by bslinger** [madewithlove/elasticsearcher#47]
Types have been removed as of ES 6+, and the suggestion from Elastic is to re-index and store `_type` in a `type` field, as per https://www.elastic.co/blog/index-type-parent-child-join-now-future-in-elasticsearch

Is it possible there could be an intermediate version of Elastic Searcher which kept the same API for defining types, but modified the query to add a filter for that `type` field (configurable would probably be nice)?

**Comment by dieterve** [comment]
Interesting, I am however not a fan of prolonging the deprecation period of elasticsearch. It seems sensible to support types for as long as elasticsearch supports it. I prefer to keep this package its API as close to elasticsearch as possible and supporting types while elasticsearch doesn't, does not fit in that strategy. That means not doing anything special in this package but requiring the end-user to implement the backwards compatibility.

**Comment by slashrsm** [comment]
This is now done in `0.7.x` branch.

**Comment by slashrsm** [comment]
See #59 for changes.
